services:
  mysql:
    image: mysql:8.0
    container_name: mysql-bandas
    environment:
      MYSQL_DATABASE: bandas_db_user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bandas_user
      MYSQL_PASSWORD: bandas_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bandas-network

volumes:
  mysql_data:

networks:
  bandas-network:
