services:
  # Configuración del servicio MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql-bandas
    environment:
      # Variables de entorno para configurar la base de datos
      MYSQL_DATABASE: bandas_db_user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bandas_user
      MYSQL_PASSWORD: bandas_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bandas-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD --silent"] # Comando para verificar si MySQL está listo para conexiones
      interval: 5s # Intervalo entre chequeos
      timeout: 3s # Tiempo máximo para que el chequeo se complete
      retries: 5 # Número de reintentos antes de considerar que el servicio no está saludable

  usuarios:
    build: . # Construir la imagen desde el Dockerfile en el directorio actual
    image: ismabc4/usuarios:local # Nombre de la imagen
    container_name: usuarios
    depends_on:
        mysql:
            condition: service_healthy # Esperar a que MySQL esté "saludable" antes de iniciar este servicio, es decir, listo para conexiones
    environment:
      # Se utiliza la URL de MySQL del servicio, no localhost porque ambos están en la misma red de Docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bandas_db_user?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: bandas_user
      SPRING_DATASOURCE_PASSWORD: bandas_pass
      SPRING_PROFILES_ACTIVE: prod
    ports: ["8080:8080"]
    networks: [bandas-network]

volumes:
  mysql_data:

networks:
  bandas-network:
