version: "3.8"

services:
  usuarios:
    # En desarrollo, no construimos la imagen con Maven cada vez
    build: .
    volumes:
      # Monta el JAR local generado en target dentro del contenedor
      - ./target/usuarios-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: sh -c "java -jar /app/app.jar"

# De esta manera en local podemos hacer cambios, recompilar el JAR con Maven y
# simplemente reiniciar el contenedor para ver los cambios reflejados.
# En producción, usaremos la imagen ya construida y subida a Docker Hub.
# Esto es útil para desarrollo local, pero en producción usaremos la imagen ya construida y subida a Docker Hub.
# Así evitamos tener que reconstruir la imagen cada vez que hacemos un cambio.

# Uso:
# 1. Compila el proyecto con Maven para generar el JAR:
#    mvn clean package -DskipTests
# 2. Inicia los servicios con Docker Compose:
#    docker-compose up --build
# 3. Cuando hagas cambios en el código, recompila el JAR y reinicia el contenedor:
#    mvn clean package -DskipTests
#    docker-compose restart usuarios