server:
  port: 8081

spring:
  application:
      name: usuarios
  datasource:
    url: jdbc:mysql://localhost:3307/tfm_users?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: tfm_users_rw
    password: tfm_users_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Usar 'create' si quieres que borre y rehaga todo en cada arranque
        # Usar 'update' para que actualice el esquema sin perder datos
      # Usar 'validate' para validar el esquema sin hacer cambios
      # Usar 'none' para no hacer nada con el esquema
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/tfm-bandas
          # Alternativa equivalente:
          # jwk-set-uri: http://localhost:8080/realms/tfm/protocol/openid-connect/certs


logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true